$background = 030305
$onBackground = e6e4f0
$surface = 030305
$surfaceDim = 030305
$surfaceBright = 0c0c11
$surfaceContainerLowest = 000000
$surfaceContainerLow = 040407
$surfaceContainer = 06060b
$surfaceContainerHigh = 08080d
$surfaceContainerHighest = 0a0b10
$onSurface = e6e4f0
$surfaceVariant = 0a0b10
$onSurfaceVariant = abaab5
$outline = 75747f
$outlineVariant = 474750
$inverseSurface = fcf8fe
$inverseOnSurface = 55545a
$shadow = 000000
$scrim = 000000
$surfaceTint = 262735
$primary = c2c3ee
$primaryDim = b4b5e0
$onPrimary = 3b3d61
$primaryContainer = 4d4f74
$onPrimaryContainer = e1e1ff
$inversePrimary = 5a5c82
$primaryFixed = d0d1fd
$primaryFixedDim = c2c3ee
$onPrimaryFixed = 313356
$onPrimaryFixedVariant = 4d4f74
$secondary = c5c4dd
$secondaryDim = b7b7cf
$onSecondary = 3e3f52
$secondaryContainer = 393a4d
$onSecondaryContainer = bebdd5
$secondaryFixed = e1e0f9
$secondaryFixedDim = d3d2eb
$onSecondaryFixed = 3d3e51
$onSecondaryFixedVariant = 595a6f
$tertiary = fee3ff
$tertiaryDim = f7d0fd
$onTertiary = 6a4c71
$tertiaryContainer = f7d0fd
$onTertiaryContainer = 614468
$tertiaryFixed = f7d0fd
$tertiaryFixedDim = e9c2ee
$onTertiaryFixed = 4d3155
$onTertiaryFixedVariant = 6c4d72
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 72749b
$secondaryPaletteKeyColor = 75758b
$tertiaryPaletteKeyColor = 8d6c93
$neutralPaletteKeyColor = 78767c
$neutralVariantPaletteKeyColor = 777680
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 72749b
$secondary_paletteKeyColor = 75758b
$tertiary_paletteKeyColor = 8d6c93
$neutral_paletteKeyColor = 78767c
$neutral_variant_paletteKeyColor = 777680
$term0 = 080808
$term1 = a775ff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 97aad7
$term5 = b19feb
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = bc95ff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b4c1dc
$term13 = c7b5f5
$term14 = bae0ff
$term15 = ffffff
$rosewater = f7eff9
$flamingo = e8def3
$pink = e0d8ff
$mauve = bcb9ff
$red = bea6fe
$maroon = c7b6ee
$peach = e0c2f9
$yellow = ffecf3
$green = c8e3ff
$teal = d2e0ff
$sky = cedaff
$sapphire = b5c5ff
$blue = aeb8ff
$lavender = c5c9ff
$klink = 7083d2
$klinkSelection = 7083d2
$kvisited = 7d73db
$kvisitedSelection = 7e73db
$knegative = 9c6aff
$knegativeSelection = 9c69ff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = e6e4f0
$subtext1 = abaab5
$subtext0 = 75747f
$overlay2 = 19181a
$overlay1 = 161617
$overlay0 = 131215
$surface2 = 0f0f11
$surface1 = 0b0a0d
$surface0 = 040406
$base = 000001
$mantle = 000001
$crust = 000001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
